# Generated by Django 4.0.3 on 2023-04-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_vin_alter_technician_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AddField(
            model_name='status',
            name='status_id',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
